### ISSUE TITLE
test air-gapped deploy

### ISSUE THREAD

**Issue by tompscanlan** [vmware/vmware-pks-deploy#14]
1. create a onecloud vpod based on NSBU-2018-01-NSX-T-Base-Deploy-v1.3
1. The esxi hosts in this vpod need to be re-sized to have at least 4 CPUs each
1. capture this vpod for future use in testing
1. add an iptables rule in the vpod router to block outbound traffic
1. capture an ova from a bootstrap vm that has downloaded all binaries, and stored docker images in minio
1.  deploy that ova in the onecloud instance
1. create a valid param file for onecloud (probably start from https://github.com/NiranEC77/NSX-T-Concourse-Pipeline-Onecloud-param/blob/master/one-cloud-param.yaml)
1. run deploy and test for a valid deployment

**Comment by tdhite** [comment]
Closing this as it has shifted to pivotalservices as part of ongoing work in the pipeline projects.
